<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\UserRepository;
use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends UserRepository
{
//    public function getLoggedUserId(User $user)
//    {
//        return $this->findBy('user_id', $user->getId());
//    }
}
